"""
FactoryAI — v1 Skeleton
A FastAPI skeleton for a manufacturing knowledge chatbot.
No AI model used in this iteration — responses are hardcoded.
See spec.md for full design rationale.
"""

from fastapi import FastAPI
from pydantic import BaseModel
from typing import Optional

# ---------------------------------------------------------------------------
# App initialisation
# ---------------------------------------------------------------------------

app = FastAPI(
    title="FactoryAI",
    description=(
        "Manufacturing knowledge chatbot API. "
        "v1: hardcoded skeleton. v2 will connect to RAG pipeline with pgvector."
    ),
    version="1.0.0",
)


# ---------------------------------------------------------------------------
# Data models (Pydantic)
# Defined here separately from route logic — easy to move to models.py in v2
# ---------------------------------------------------------------------------

class Citation(BaseModel):
    source: str
    link: Optional[str] = None
    page_number: Optional[int] = None


class RelatedSource(BaseModel):
    title: str
    link: Optional[str] = None


class AskRequest(BaseModel):
    question: str
    session_id: Optional[str] = None  # unused in v1, reserved for multi-turn in v2


class AskResponse(BaseModel):
    answer: str
    citations: list[Citation]
    related_sources: list[RelatedSource]


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.get("/health")
def health_check():
    """Simple liveness probe. Returns 200 if the service is running."""
    return {"status": "ok", "version": "1.0.0"}


@app.post("/api/v1/ask", response_model=AskResponse)
def ask(request: AskRequest) -> AskResponse:
    """
    Accept a natural language question about manufacturing equipment or procedures.
    Returns an answer with source citations.

    v1: hardcoded response — demonstrates API contract and schema.
    v2: will replace this with a RAG pipeline (LLM + pgvector similarity search).
    """
    # Hardcoded response — to be replaced with RAG logic in v2
    return AskResponse(
        answer=(
            f"[v1 hardcoded] You asked: '{request.question}'. "
            "In v2, this answer will be generated by an LLM using retrieved "
            "equipment documentation from the vector store."
        ),
        citations=[
            Citation(
                source="Conveyor Belt Maintenance Manual CB-04",
                link=None,
                page_number=42,
            )
        ],
        related_sources=[
            RelatedSource(
                title="General Preventive Maintenance Schedule — Line 3",
                link=None,
            ),
            RelatedSource(
                title="Equipment Fault Code Reference v2.1",
                link=None,
            ),
        ],
    )
