"""
FactoryAI — v2
--------------
Wires /api/v1/ask to the real RAG query pipeline in query.py.
v1 hardcoded stub replaced with live embeddings + gpt-4o-mini.

See spec.md and spec_query.md for design rationale.
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import Optional

import query

# ---------------------------------------------------------------------------
# App initialisation
# ---------------------------------------------------------------------------
app = FastAPI(
    title="FactoryAI",
    description=(
        "Manufacturing knowledge chatbot API. "
        "v2: RAG pipeline — local embeddings (all-MiniLM-L6-v2) + gpt-4o-mini."
    ),
    version="2.0.0",
)


# ---------------------------------------------------------------------------
# Data models (Pydantic)
# ---------------------------------------------------------------------------
class Citation(BaseModel):
    source: str
    link: Optional[str] = None
    page_number: Optional[int] = None


class RelatedSource(BaseModel):
    title: str
    link: Optional[str] = None


class AskRequest(BaseModel):
    question: str
    session_id: Optional[str] = None   # reserved for multi-turn in v3


class AskResponse(BaseModel):
    answer: str
    citations: list[Citation]
    related_sources: list[RelatedSource]


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------
@app.get("/health")
def health_check():
    """Simple liveness probe. Returns 200 if the service is running."""
    return {"status": "ok", "version": "2.0.0"}


@app.post("/api/v1/ask", response_model=AskResponse)
def ask(request: AskRequest) -> AskResponse:
    """
    Accept a natural language question about manufacturing equipment or procedures.
    Runs the full RAG pipeline: embed → retrieve → prompt → LLM → respond.

    Citations are sourced from retrieval metadata — not generated by the LLM.
    Returns 503 if the vector store hasn't been built yet (run ingest.py first).
    """
    try:
        result = query.run(request.question)
        return AskResponse(**result)
    except FileNotFoundError as e:
        raise HTTPException(status_code=503, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Query pipeline error: {str(e)}")
